name: Delete Neon Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Neon Branch
      uses: neondatabase/delete-branch-by-name-action.yml@main
      with:
        project_id: ${{ secrets.NEON_PROJECT_ID }}
        branch_name: ${{ github.head_ref || github.ref_name }}
        api_key: ${{ secrets.NEON_API_KEY }}

    - name: Delete KV entry
      run: |
        echo -e "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_KV_EDIT_API_TOKEN }}\nCLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> .env
        npx wrangler kv:key delete ${{ github.head_ref || github.ref_name }} --namespace-id=60aa73f01b8646e596c40c13060458e9
      