name: Deploy Preview

on: [pull_request]

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn install --prefer-offline --frozen-lockfile

      # - name: Get PR sha
      #   id: get_pull_request_sha
      #   run: |
      #     pull_request_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH" | cut -c1-8)
      #     echo "pull_request_sha=${pull_request_sha}" >> $GITHUB_OUTPUT
      #     echo $pull_request_sha

      - name: Neon Database Create Branch Action
        uses: neondatabase/create-branch-action@v4
        id: create_branch
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ github.head_ref || github.ref_name }}
          api_key: ${{ secrets.NEON_API_KEY }}

      # - name: Run Drizzle-ORM Migrations
      #   run: |
      #     touch .env
      #     echo DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler}}/neondb >> .env
      #     yarn run-migrations
      - name: Write Neon Database URL to KV
        run: |
          echo -e "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_KV_EDIT_API_TOKEN }}\nCLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> .env
          npx wrangler kv:key put ${{ github.head_ref || github.ref_name }} ${{ steps.create_branch.outputs.db_url_with_pooler}} --namespace-id=60aa73f01b8646e596c40c13060458e9

      - name: Build Project Artifacts
        run: npx @cloudflare/next-on-pages@1

      - name: Deploy to Cloudflare
        uses: cloudflare/pages-action@1
        id: deploy-to-cloudflare
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_EDIT_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kysely-poc
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Cloudflare Preview URL :rocket: : ${{ steps.deploy-to-cloudflare.outputs.url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}